FROM node:18-alpine

WORKDIR /app

RUN apk update && apk add --no-cache yt-dlp ffmpeg

RUN corepack enable && corepack prepare pnpm@9.15.4 --activate

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY apps ./apps
COPY packages ./packages

RUN pnpm install --frozen-lockfile

RUN pnpm exec turbo run build --filter=@repo/train-ai-worker

ENV NODE_ENV=production

CMD ["node", "packages/train-ai-worker/dist/main.js"]
